### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by firdavsDev** [davidkuda/blog-kuda-ai#2]
I love ur blog website and I opened it at night (3AM). Wow my eyes injured :(

Let me try my best to add Dark theme this repo ;)

**Comment by davidkuda** [comment]
Hey @firdavsDev thank you so much for checking out my website and this repo, and for opening an issue, I appreciate that. Out of curiosity, how did you land on my website? :) 

I can totally relate to that feeling, I had it a few times, too. To have a consistent dark mode browsing on all devices, I use [Dark Reader](https://darkreader.org/) and can highly recommend using it. It's even available on mobile devices.

Had a native dark mode on my todo list, but yeah, got carried away with life and didn't do it yet.

My best wishes to you from Berlin!

**Comment by firdavsDev** [comment]
> Hey @firdavsDev thank you so much for checking out my website and this repo, and for opening an issue, I appreciate that. Out of curiosity, how did you land on my website? :)
> 
> I can totally relate to that feeling, I had it a few times, too. To have a consistent dark mode browsing on all devices, I use [Dark Reader](https://darkreader.org/) and can highly recommend using it. It's even available on mobile devices.
> 
> Had a native dark mode on my todo list, but yeah, got carried away with life and didn't do it yet.
> 
> My best wishes to you from Berlin!


Hi @davidkuda thanks for answer bro. 

I am a Senior google searcher (git repo forker) developer so I searched `how to configure my Iterm2 terminal` and Google search engine recommendation ur blog. So then I wanna develop dark mode for ur awesome blog website.

Thanks for useful blogs and I find my problem solution on ur blogs

My best wishes to you from Uzbekistan!
